// File generated by flutterfire_cli.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// A class that exposes all Firebase options for different platforms.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDspVwl5wvtDz_pjkkf-4Eret4uKN5SZYE',
    appId: '1:450994012049:web:a4fd58a7a3a0961d166430',
    messagingSenderId: '450994012049',
    projectId: 'mindconnect-ddb26',
    authDomain: 'mindconnect-ddb26.firebaseapp.com',
    storageBucket: 'mindconnect-ddb26.firebasestorage.app',
  );

  // For Android platform - uses google-services.json
  // No need to configure here; Android uses google-services.json

  // For iOS platform - uses GoogleService-Info.plist
  // No need to configure here; iOS uses GoogleService-Info.plist
}
